### 1. What does Pandas stand for?
##### It stands for either Panal Data or Python Data Analysis
### 2. What are the 2 collections used in Pandas?
##### Series and Dataframes
### 3. Name 4 things Pandas can do for us.
##### Pandas can load, manipulate, prepare, model and analyze 
### 4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
##### inplace=True
### 5. What is a CSV
##### A csv is a type of data file
### 6. When cleaning data what values do we not like in our data?
##### Null values


In [20]:
# Do NOT do questions 10, 17, 18, 19.
# 7 Import NumPy, use one of the NumPy methods and create an array with a shape of ... (2, 3, 2). You can use the reshape method -- .reshape()
import numpy as np
import pandas as pd
a1=np.random.rand(2,3,2)
print(a1)

[[[0.32651573 0.09497481]
  [0.26571413 0.05470751]
  [0.92326718 0.21918041]]

 [[0.50726528 0.36727106]
  [0.02845554 0.94780732]
  [0.10281105 0.31656981]]]


In [21]:
# 8 Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20
a=np.linspace(0,20,num=6)
a

array([ 0.,  4.,  8., 12., 16., 20.])

In [22]:
# 9 Make a Deep Copy of the above array
import copy as cp
b=cp.deepcopy(a)
b

array([ 0.,  4.,  8., 12., 16., 20.])

In [23]:
# 11 Concatenate these 3 arrays into a new array named 'newArray'...
a =np.array([[25, 16]])
b=np.array([[11, 2], [13, 4]])
c=np.array([[7, 81], [5, 6], [11, 12]])
newArray=np.concatenate((a,b,c),axis=0)
print(newArray)



[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [24]:
# 12 Sort 'newArray' in order into 'sortedArray'
sortedArray=np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [25]:
#Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.
reshapedArray=sortedArray.reshape(2,2,3)
reshapedArray

array([[[16, 25,  2],
        [11,  4, 13]],

       [[ 7, 81,  5],
        [ 6, 11, 12]]])

In [31]:
# 14 Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.
a,b=reshapedArray
c,d=a
e,f=b
print("The four variables are \n","c=",c,'\n',"d=",d,'\n',"e=",e,'\n',"f=",f)

The four variables are 
 c= [16 25  2] 
 d= [11  4 13] 
 e= [ 7 81  5] 
 f= [ 6 11 12]


In [44]:
# 15 Combined and sort the following arrays into one called 'comboArray' ...
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
new=np.concatenate((one,two,three))
comboArray=np.sort(new)
print(comboArray)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [57]:
# 16 Take 'comboArray' and perform the following slicing activities:

print("sec1 - the 2nd element")
print(comboArray[1])
print("sec2 - all elements from the 3rd element to the last")
print(comboArray[2:])
print("sec3 - all elements from the 4th to the 14th elements")
print(comboArray[3:14])
print("sec4 - the last 6 elements")
print(comboArray[-6:])
print("sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.")
print(comboArray[-28:])
print("sec6 - from #20 every even element to the end")
print(comboArray[20:28:2])
print("sec7 - from the last element moving forward, every 5th element.")
print(-np.sort(-comboArray)[0:28:5])

sec1 - the 2nd element
1
sec2 - all elements from the 3rd element to the last
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec3 - all elements from the 4th to the 14th elements
[ 3  4  5  6  7 10 11 12 13 14 15]
sec4 - the last 6 elements
[22 23 24 25 26 27]
sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec6 - from #20 every even element to the end
[24 26]
sec7 - from the last element moving forward, every 5th element.
[27 22 15 10  3]


In [ ]:
# 20 Using Series, create a DataFrame that looks like this:

In [ ]:
# 21 Using Series, create a DataFrame that looks like this:
df= {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }

In [ ]:
# 22 Add a new column to the DataFrame with the following deserts: 
# ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

In [ ]:
# 23 Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

In [ ]:
# 24 Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

In [ ]:
# 25 (A) Using Pandas, make your own .CSV file with data on vegetables and save it. 
# (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.