### 1. What does Pandas stand for?
#####
### 2. What are the 2 collections used in Pandas?
#####
### 3. Name 4 things Pandas can do for us.
#####
### 4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
#####
### 5. What is a CSV
#####
### 6. When cleaning data what values do we not like in our data?
#####


In [3]:
# Do NOT do questions 10, 17, 18, 19.
# 7 Import NumPy, use one of the NumPy methods and create an array with a shape of ... (2, 3, 2). You can use the reshape method -- .reshape()
import numpy as np
import pandas as pd
a1=np.random.rand(2,3,2)
print(a1)

[[[0.36040377 0.05092494]
  [0.73806246 0.27566888]
  [0.30292447 0.93732493]]

 [[0.90116244 0.11810812]
  [0.79606821 0.22303304]
  [0.93304279 0.2723093 ]]]


In [ ]:
# 8 Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

In [ ]:
# 9 Make a Deep Copy of the above array

In [5]:
# 11 Concatenate these 3 arrays into a new array named 'newArray'...
a =np.array([[25, 16]])
b=np.array([[11, 2], [13, 4]])
c=np.array([[7, 81], [5, 6], [11, 12]])
newArray=np.concatenate((a,b,c),axis=0)
print(newArray)



[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [6]:
# 12 Sort 'newArray' in order into 'sortedArray'
sortedArray=np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [7]:
#Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.
a,b=sortedArray

ValueError: too many values to unpack (expected 2)

In [ ]:
# 14 Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

In [ ]:
# 15 Combined and sort the following arrays into one called 'comboArray' ...

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
""" 16 Take 'comboArray' and perform the following slicing activities:

print sec1 - the 2nd element
print sec2 - all elements from the 3rd element to the last
print sec3 - all elements from the 4th to the 14th elements
print sec4 - the last 6 elements
print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print sec6 - from #20 every even element to the end
print sec7 - from the last element moving forward, every 5th element.
""" 